### ISSUE TITLE
This Launcher is based on Android10?

### ISSUE THREAD

**Issue by xiangwencui** [toeii/Launcher3#1]
我想在Android10上应用负一屏的功能，遇到关于shortcut被分割的问题，请问你的代码是基于Android10的Launcher3吗？

**Comment by toeii** [comment]
基于Android N，兼容Android10

**Comment by toeii** [comment]
负一屏可以在Launcher.populateCustomContentContainer中自定义加载你想要的View，并不会影响其他CellLayout中的Shortcut
